[control]
rhce-control ansible_host=192.168.40.200

[nodes]
rhce-node-01 ansible_host=192.168.40.201
rhce-node-02 ansible_host=192.168.40.202
rhce-node-03 ansible_host=192.168.40.203
rhce-node-04 ansible_host=192.168.40.204
rhce-node-05 ansible_host=192.168.40.205

[rhce:children]
control
nodes

[proxy]
proxy-01 ansible_host=192.168.40.210

[app]
app-01 ansible_host=192.168.40.211

[db]
db-01 ansible_host=192.168.40.212

[dns]
dns-01 ansible_host=192.168.40.213

[infra:children]
proxy
app
db
dns

[all:vars]
ansible_user=ansible
ansible_ssh_private_key_file=~/.ssh/id_ed25519
ansible_python_interpreter=/usr/bin/python3
